/**
 * @file simpleDes.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE simpleDes.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "simpleDes.h"
#include "type.h"
#include "networkinterface.h"
#include "C4SNet.h"
#include "distribution.h"
#include "list.h"
#include <stdlib.h>
#include "../scc.h"

char *snet_simpleDes_labels[] = {
	"E__simpleDes__None",
	"pt",
	"key",
	"D",
	"K",
	"ct",
	"interval",
	"mess",
	"C"};

char *snet_simpleDes_interfaces[] = {
	"C4SNet"};

extern void *source(void *hnd, int arg_0, int arg_1);

static snet_handle_t *SNetExeRealm_create__source(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__source(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__source(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__source(snet_handle_t *handle, int arg_0, int arg_1)
{
  return source(handle, arg_0, arg_1);
}

static snet_handle_t *SNet__simpleDes__source(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  int stag_interval = 0;
  int stag_mess = 0;

  rec = SNetHndGetRecord(hnd);

  stag_interval = SNetRecTakeTag(rec, T__simpleDes__interval);

  stag_mess = SNetRecTakeTag(rec, T__simpleDes__mess);

  return(SNetCall__source(hnd, stag_interval, stag_mess));
}

extern void *initP(void *hnd, void *arg_0, void *arg_1);

static snet_handle_t *SNetExeRealm_create__initP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__initP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__initP(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__initP(snet_handle_t *handle, void *arg_0, void *arg_1)
{
  return initP(handle, arg_0, arg_1);
}

static snet_handle_t *SNet__simpleDes__initP(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_pt = NULL;
  void *field_key = NULL;

  rec = SNetHndGetRecord(hnd);

  field_pt = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__pt));

  field_key = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__key));

  return(SNetCall__initP(hnd, field_pt, field_key));
}

extern void *subRound(void *hnd, void *arg_0, void *arg_1, int arg_2);

static snet_handle_t *SNetExeRealm_create__subRound(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__subRound(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__subRound(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__subRound(snet_handle_t *handle, void *arg_0, void *arg_1, int arg_2)
{
  return subRound(handle, arg_0, arg_1, arg_2);
}

static snet_handle_t *SNet__simpleDes__subRound(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_D = NULL;
  void *field_K = NULL;
  int stag_C = 0;

  rec = SNetHndGetRecord(hnd);

  field_D = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__D));

  field_K = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__K));

  stag_C = SNetRecTakeTag(rec, T__simpleDes__C);

  return(SNetCall__subRound(hnd, field_D, field_K, stag_C));
}

extern void *finalP(void *hnd, void *arg_0, void *arg_1, int arg_2);

static snet_handle_t *SNetExeRealm_create__finalP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__finalP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__finalP(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__finalP(snet_handle_t *handle, void *arg_0, void *arg_1, int arg_2)
{
  return finalP(handle, arg_0, arg_1, arg_2);
}

static snet_handle_t *SNet__simpleDes__finalP(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_D = NULL;
  void *field_K = NULL;
  int stag_C = 0;

  rec = SNetHndGetRecord(hnd);

  field_D = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__D));

  field_K = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__K));

  stag_C = SNetRecTakeTag(rec, T__simpleDes__C);

  return(SNetCall__finalP(hnd, field_D, field_K, stag_C));
}

extern void *sink(void *hnd, void *arg_0);

static snet_handle_t *SNetExeRealm_create__sink(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__sink(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__sink(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__sink(snet_handle_t *handle, void *arg_0)
{
  return sink(handle, arg_0);
}

static snet_handle_t *SNet__simpleDes__sink(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_ct = NULL;

  rec = SNetHndGetRecord(hnd);

  field_ct = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__ct));

  return(SNetCall__sink(hnd, field_ct));
}

static snet_stream_t *SNet__simpleDes___IN___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, 1, "source", 
              &SNet__simpleDes__source, 
              &SNetExeRealm_create__source, 
              &SNetExeRealm_update__source, 
              &SNetExeRealm_destroy__source, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(4, field, F__simpleDes__pt, field, F__simpleDes__key)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, 13, "initP", 
              &SNet__simpleDes__initP, 
              &SNetExeRealm_create__initP, 
              &SNetExeRealm_update__initP, 
              &SNetExeRealm_destroy__initP, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(6, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SL___SR___ST(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(6, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C)));

  return (out_buf);
}

static snet_stream_t *SNet____STAR_INCARNATE_simpleDes___IN___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetStarIncarnate(in_buf, info, location, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(0), 
                  SNetIntListCreate(1, T__simpleDes__C), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(1, 
                SNetEeq( 
                  SNetEtag( T__simpleDes__C), 
                  SNetEconsti( 2))), 
              &SNet__simpleDes___IN___SL___SL___SR___ST, 
              &SNet____STAR_INCARNATE_simpleDes___IN___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetStar(in_buf, info, location, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(0), 
                  SNetIntListCreate(1, T__simpleDes__C), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(1, 
                SNetEeq( 
                  SNetEtag( T__simpleDes__C), 
                  SNetEconsti( 2))), 
              &SNet__simpleDes___IN___SL___SL___SR___ST, 
              &SNet____STAR_INCARNATE_simpleDes___IN___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, 113, "finalP", 
              &SNet__simpleDes__finalP, 
              &SNetExeRealm_create__finalP, 
              &SNetExeRealm_update__finalP, 
              &SNetExeRealm_destroy__finalP, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(2, field, F__simpleDes__ct)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SL, 
              &SNet__simpleDes___IN___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, 2, "sink", 
              &SNet__simpleDes__sink, 
              &SNetExeRealm_create__sink, 
              &SNetExeRealm_update__sink, 
              &SNetExeRealm_destroy__sink, 
              SNetIntListListCreate(0));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL, 
              &SNet__simpleDes___IN___SR);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_IN__simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, SNET__simpleDes__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(2, T__simpleDes__interval, T__simpleDes__mess), 
                SNetIntListCreate(0)));

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_BODY__simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_IN__simpleDes, 
              &SNet__simpleDes___IN);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_OUT__simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, -SNET__simpleDes__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(0), 
                SNetIntListCreate(0)));

  return (out_buf);
}

snet_stream_t *SNet__simpleDes___simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;
  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_BODY__simpleDes,
              &SNet____SHIELD_OUT__simpleDes);

  return (out_buf);
}

int SNetNetToId(snet_startup_fun_t fun)
{
  if (fun == &SNet__simpleDes___IN___SL___SL___SR___ST) {
    return 1;
  }

  return -1;
}

snet_startup_fun_t SNetIdToNet(int id)
{
  if (id == 1) {
    return &SNet__simpleDes___IN___SL___SL___SR___ST;
  }

  return NULL;
}

int SNetMain__simpleDes(int argc, char* argv[])
{
  int i,numWorkers = 0,ret = 0;
  for (i=0; i<argc; i++) {
    if(strcmp(argv[i], "-w") == 0) {
			/* Number of workers */
			i++;
			numWorkers = atoi(argv[i]);
		}
  }
  SCCInit(0,numWorkers,2,"/shared/nil/nk.host");

  if(SCCIsMaster()){
    C4SNetInit(I__simpleDes__C4SNet, 0);
  
    ret = SNetInRun(argc, argv,
              snet_simpleDes_labels,
              SNET__simpleDes__NUMBER_OF_LABELS,
              snet_simpleDes_interfaces,
              SNET__simpleDes__NUMBER_OF_INTERFACES,
              SNet__simpleDes___simpleDes);

    SNetInterfacesDestroy();
  }else{
    ret = SNetInRunWorker(argc, argv);
  }
  SCCStop();

  return( ret);
}

