/**
 * @file fft.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE fft.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "fft.h"
#include "type.h"
#include "networkinterface.h"
#include "C4SNet.h"
#include "distribution.h"
#include "list.h"

#include <stdlib.h>
#include <stdio.h>
#include "/shared/nil/snetInstall/include/scc.h"

char *snet_fft_labels[] = {
	"E__fft__None",
	"X",
	"Y",
	"W",
	"mess",
	"LN",
	"size",
	"num_node",
	"sleep_micro",
	"change_mess",
	"change_percent",
	"window_size",
	"thresh_hold",
	"skip_update",
	"node",
	"S"};

char *snet_fft_interfaces[] = {
	"C4SNet"};

extern void *snet_source(void *hnd, int arg_0, int arg_1, int arg_2, int arg_3, int arg_4, int arg_5, int arg_6, int arg_7, int arg_8, int arg_9);

static snet_handle_t *SNetExeRealm_create__snet_source(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__snet_source(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__snet_source(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__snet_source(snet_handle_t *handle, int arg_0, int arg_1, int arg_2, int arg_3, int arg_4, int arg_5, int arg_6, int arg_7, int arg_8, int arg_9)
{
  return snet_source(handle, arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6, arg_7, arg_8, arg_9);
}

static snet_handle_t *SNet__fft__snet_source(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  int stag_mess = 0;
  int stag_LN = 0;
  int stag_size = 0;
  int stag_num_node = 0;
  int stag_sleep_micro = 0;
  int stag_change_mess = 0;
  int stag_change_percent = 0;
  int stag_window_size = 0;
  int stag_thresh_hold = 0;
  int stag_skip_update = 0;

  rec = SNetHndGetRecord(hnd);

  stag_mess = SNetRecTakeTag(rec, T__fft__mess);

  stag_LN = SNetRecTakeTag(rec, T__fft__LN);

  stag_size = SNetRecTakeTag(rec, T__fft__size);

  stag_num_node = SNetRecTakeTag(rec, T__fft__num_node);

  stag_sleep_micro = SNetRecTakeTag(rec, T__fft__sleep_micro);

  stag_change_mess = SNetRecTakeTag(rec, T__fft__change_mess);

  stag_change_percent = SNetRecTakeTag(rec, T__fft__change_percent);

  stag_window_size = SNetRecTakeTag(rec, T__fft__window_size);

  stag_thresh_hold = SNetRecTakeTag(rec, T__fft__thresh_hold);

  stag_skip_update = SNetRecTakeTag(rec, T__fft__skip_update);

  return(SNetCall__snet_source(hnd, stag_mess, stag_LN, stag_size, stag_num_node, stag_sleep_micro, stag_change_mess, stag_change_percent, stag_window_size, stag_thresh_hold, stag_skip_update));
}

extern void *initP(void *hnd, void *arg_0, int arg_1, int arg_2, int arg_3);

static snet_handle_t *SNetExeRealm_create__initP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__initP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__initP(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__initP(snet_handle_t *handle, void *arg_0, int arg_1, int arg_2, int arg_3)
{
  return initP(handle, arg_0, arg_1, arg_2, arg_3);
}

static snet_handle_t *SNet__fft__initP(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_X = NULL;
  int stag_LN = 0;
  int stag_size = 0;
  int stag_node = 0;

  rec = SNetHndGetRecord(hnd);

  field_X = SNetRefTakeData(SNetRecTakeField(rec, F__fft__X));

  stag_LN = SNetRecTakeTag(rec, T__fft__LN);

  stag_size = SNetRecTakeTag(rec, T__fft__size);

  stag_node = SNetRecTakeTag(rec, T__fft__node);

  return(SNetCall__initP(hnd, field_X, stag_LN, stag_size, stag_node));
}

extern void *stepP(void *hnd, void *arg_0, void *arg_1, void *arg_2, int arg_3, int arg_4, int arg_5, int arg_6);

static snet_handle_t *SNetExeRealm_create__stepP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__stepP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__stepP(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__stepP(snet_handle_t *handle, void *arg_0, void *arg_1, void *arg_2, int arg_3, int arg_4, int arg_5, int arg_6)
{
  return stepP(handle, arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
}

static snet_handle_t *SNet__fft__stepP(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_X = NULL;
  void *field_Y = NULL;
  void *field_W = NULL;
  int stag_S = 0;
  int stag_LN = 0;
  int stag_size = 0;
  int stag_node = 0;

  rec = SNetHndGetRecord(hnd);

  field_X = SNetRefTakeData(SNetRecTakeField(rec, F__fft__X));

  field_Y = SNetRefTakeData(SNetRecTakeField(rec, F__fft__Y));

  field_W = SNetRefTakeData(SNetRecTakeField(rec, F__fft__W));

  stag_S = SNetRecTakeTag(rec, T__fft__S);

  stag_LN = SNetRecTakeTag(rec, T__fft__LN);

  stag_size = SNetRecTakeTag(rec, T__fft__size);

  stag_node = SNetRecTakeTag(rec, T__fft__node);

  return(SNetCall__stepP(hnd, field_X, field_Y, field_W, stag_S, stag_LN, stag_size, stag_node));
}

extern void *snet_sink(void *hnd, void *arg_0, void *arg_1, void *arg_2, int arg_3, int arg_4, int arg_5, int arg_6);

static snet_handle_t *SNetExeRealm_create__snet_sink(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__snet_sink(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__snet_sink(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__snet_sink(snet_handle_t *handle, void *arg_0, void *arg_1, void *arg_2, int arg_3, int arg_4, int arg_5, int arg_6)
{
  return snet_sink(handle, arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
}

static snet_handle_t *SNet__fft__snet_sink(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_X = NULL;
  void *field_Y = NULL;
  void *field_W = NULL;
  int stag_S = 0;
  int stag_LN = 0;
  int stag_size = 0;
  int stag_node = 0;

  rec = SNetHndGetRecord(hnd);

  field_X = SNetRefTakeData(SNetRecTakeField(rec, F__fft__X));

  field_Y = SNetRefTakeData(SNetRecTakeField(rec, F__fft__Y));

  field_W = SNetRefTakeData(SNetRecTakeField(rec, F__fft__W));

  stag_S = SNetRecTakeTag(rec, T__fft__S);

  stag_LN = SNetRecTakeTag(rec, T__fft__LN);

  stag_size = SNetRecTakeTag(rec, T__fft__size);

  stag_node = SNetRecTakeTag(rec, T__fft__node);

  return(SNetCall__snet_sink(hnd, field_X, field_Y, field_W, stag_S, stag_LN, stag_size, stag_node));
}

static snet_stream_t *SNet__fft___IN___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "snet_source", 
              &SNet__fft__snet_source, 
              &SNetExeRealm_create__snet_source, 
              &SNetExeRealm_update__snet_source, 
              &SNetExeRealm_destroy__snet_source, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__fft__X, tag, T__fft__LN, tag, T__fft__size, tag, T__fft__node)));

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN___SL___SR___IS___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "initP", 
              &SNet__fft__initP, 
              &SNetExeRealm_create__initP, 
              &SNetExeRealm_update__initP, 
              &SNetExeRealm_destroy__initP, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(14, field, F__fft__X, field, F__fft__Y, field, F__fft__W, tag, T__fft__S, tag, T__fft__LN, tag, T__fft__size, tag, T__fft__node)));

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN___SL___SR___IS___SR___ST(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "stepP", 
              &SNet__fft__stepP, 
              &SNetExeRealm_create__stepP, 
              &SNetExeRealm_update__stepP, 
              &SNetExeRealm_destroy__stepP, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(14, field, F__fft__X, field, F__fft__Y, field, F__fft__W, tag, T__fft__S, tag, T__fft__LN, tag, T__fft__size, tag, T__fft__node)));

  return (out_buf);
}

static snet_stream_t *SNet____STAR_INCARNATE_fft___IN___SL___SR___IS___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetStarIncarnate(in_buf, info, location, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(0), 
                  SNetIntListCreate(2, T__fft__S, T__fft__LN), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(1, 
                SNetEeq( 
                  SNetEtag( T__fft__S), 
                  SNetEtag( T__fft__LN))), 
              &SNet__fft___IN___SL___SR___IS___SR___ST, 
              &SNet____STAR_INCARNATE_fft___IN___SL___SR___IS___SR);

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN___SL___SR___IS___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetStar(in_buf, info, location, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(0), 
                  SNetIntListCreate(2, T__fft__S, T__fft__LN), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(1, 
                SNetEeq( 
                  SNetEtag( T__fft__S), 
                  SNetEtag( T__fft__LN))), 
              &SNet__fft___IN___SL___SR___IS___SR___ST, 
              &SNet____STAR_INCARNATE_fft___IN___SL___SR___IS___SR);

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN___SL___SR___IS(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__fft___IN___SL___SR___IS___SL, 
              &SNet__fft___IN___SL___SR___IS___SR);

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSplitDet(in_buf, info, location, 
              &SNet__fft___IN___SL___SR___IS, T__fft__node, T__fft__node);

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__fft___IN___SL___SL, 
              &SNet__fft___IN___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "snet_sink", 
              &SNet__fft__snet_sink, 
              &SNetExeRealm_create__snet_sink, 
              &SNetExeRealm_update__snet_sink, 
              &SNetExeRealm_destroy__snet_sink, 
              SNetIntListListCreate(0));

  return (out_buf);
}

static snet_stream_t *SNet__fft___IN(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__fft___IN___SL, 
              &SNet__fft___IN___SR);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_IN__fft(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, SNET__fft__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(10, T__fft__mess, T__fft__LN, T__fft__size, T__fft__num_node, T__fft__sleep_micro, T__fft__change_mess, T__fft__change_percent, T__fft__window_size, T__fft__thresh_hold, T__fft__skip_update), 
                SNetIntListCreate(0)));

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_BODY__fft(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_IN__fft, 
              &SNet__fft___IN);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_OUT__fft(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, -SNET__fft__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(0), 
                SNetIntListCreate(0)));

  return (out_buf);
}

snet_stream_t *SNet__fft___fft(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;
  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_BODY__fft,
              &SNet____SHIELD_OUT__fft);

  return (out_buf);
}

int SNetNetToId(snet_startup_fun_t fun)
{
  if (fun == &SNet__fft___IN___SL___SR___IS___SR___ST) {
    return 1;
  }if (fun == &SNet__fft___IN___SL___SR___IS) {
    return 2;
  }

  return -1;
}

snet_startup_fun_t SNetIdToNet(int id)
{
  if (id == 1) {
    return &SNet__fft___IN___SL___SR___IS___SR___ST;
  }if (id == 2) {
    return &SNet__fft___IN___SL___SR___IS;
  }

  return NULL;
}

int SNetMain__fft(int argc, char* argv[])
{
  int i,numWorkers = 0, numWrappers = 0,ret = 0;
  for (i=0; i<argc; i++) {
    if(strcmp(argv[i], "-w") == 0) {
			/* Number of workers */
			i++;
			numWorkers = atoi(argv[i]);
      numWrappers = atoi(argv[++i]);
		}
  }
  //printf("work %d wrap %d\n",numWorkers,numWrappers);
  //SCCInit(numWorkers,2,"/shared/nil/nk.host");
  SCCInit(numWorkers,numWrappers,"/shared/nil/nk.host");

  if(SCCIsMaster()){
    C4SNetInit(I__fft__C4SNet, 0);
  
    ret = SNetInRun(argc, argv,
              snet_fft_labels,
              SNET__fft__NUMBER_OF_LABELS,
              snet_fft_interfaces,
              SNET__fft__NUMBER_OF_INTERFACES,
              SNet__fft___fft);

    SNetInterfacesDestroy();
  }else{
    ret = SNetInRunWorker(argc, argv);
  }
  SCCStop();

  return( ret);
}

