/**
 * @file simpleDes.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE simpleDes.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "simpleDes.h"
#include "type.h"
#include "networkinterface.h"
#include "C4SNet.h"
#include "distribution.h"
#include "list.h"
#include <stdlib.h>
#include <stdio.h>
#include "/shared/nil/snetInstall/include/scc.h"

char *snet_simpleDes_labels[] = {
	"E__simpleDes__None",
	"pt",
	"key",
	"D",
	"K",
	"ct",
	"mess",
	"size",
	"num_node",
	"node",
	"C"};

char *snet_simpleDes_interfaces[] = {
	"C4SNet"};

extern void *snet_source(void *hnd, int arg_0, int arg_1, int arg_2);

static snet_handle_t *SNetExeRealm_create__snet_source(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__snet_source(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__snet_source(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__snet_source(snet_handle_t *handle, int arg_0, int arg_1, int arg_2)
{
  return snet_source(handle, arg_0, arg_1, arg_2);
}

static snet_handle_t *SNet__simpleDes__snet_source(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  int stag_mess = 0;
  int stag_size = 0;
  int stag_num_node = 0;

  rec = SNetHndGetRecord(hnd);

  stag_mess = SNetRecTakeTag(rec, T__simpleDes__mess);

  stag_size = SNetRecTakeTag(rec, T__simpleDes__size);

  stag_num_node = SNetRecTakeTag(rec, T__simpleDes__num_node);

  return(SNetCall__snet_source(hnd, stag_mess, stag_size, stag_num_node));
}

extern void *initP(void *hnd, void *arg_0, void *arg_1, int arg_2);

static snet_handle_t *SNetExeRealm_create__initP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__initP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__initP(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__initP(snet_handle_t *handle, void *arg_0, void *arg_1, int arg_2)
{
  return initP(handle, arg_0, arg_1, arg_2);
}

static snet_handle_t *SNet__simpleDes__initP(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_pt = NULL;
  void *field_key = NULL;
  int stag_size = 0;

  rec = SNetHndGetRecord(hnd);

  field_pt = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__pt));

  field_key = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__key));

  stag_size = SNetRecTakeTag(rec, T__simpleDes__size);

  return(SNetCall__initP(hnd, field_pt, field_key, stag_size));
}

extern void *subRound(void *hnd, void *arg_0, void *arg_1, int arg_2, int arg_3);

static snet_handle_t *SNetExeRealm_create__subRound(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__subRound(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__subRound(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__subRound(snet_handle_t *handle, void *arg_0, void *arg_1, int arg_2, int arg_3)
{
  return subRound(handle, arg_0, arg_1, arg_2, arg_3);
}

static snet_handle_t *SNet__simpleDes__subRound(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_D = NULL;
  void *field_K = NULL;
  int stag_C = 0;
  int stag_size = 0;

  rec = SNetHndGetRecord(hnd);

  field_D = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__D));

  field_K = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__K));

  stag_C = SNetRecTakeTag(rec, T__simpleDes__C);

  stag_size = SNetRecTakeTag(rec, T__simpleDes__size);

  return(SNetCall__subRound(hnd, field_D, field_K, stag_C, stag_size));
}

extern void *finalP(void *hnd, void *arg_0, void *arg_1, int arg_2, int arg_3);

static snet_handle_t *SNetExeRealm_create__finalP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__finalP(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__finalP(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__finalP(snet_handle_t *handle, void *arg_0, void *arg_1, int arg_2, int arg_3)
{
  return finalP(handle, arg_0, arg_1, arg_2, arg_3);
}

static snet_handle_t *SNet__simpleDes__finalP(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_D = NULL;
  void *field_K = NULL;
  int stag_C = 0;
  int stag_size = 0;

  rec = SNetHndGetRecord(hnd);

  field_D = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__D));

  field_K = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__K));

  stag_C = SNetRecTakeTag(rec, T__simpleDes__C);

  stag_size = SNetRecTakeTag(rec, T__simpleDes__size);

  return(SNetCall__finalP(hnd, field_D, field_K, stag_C, stag_size));
}

extern void *snet_sink(void *hnd, void *arg_0, int arg_1, int arg_2);

static snet_handle_t *SNetExeRealm_create__snet_sink(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__snet_sink(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__snet_sink(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__snet_sink(snet_handle_t *handle, void *arg_0, int arg_1, int arg_2)
{
  return snet_sink(handle, arg_0, arg_1, arg_2);
}

static snet_handle_t *SNet__simpleDes__snet_sink(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_ct = NULL;
  int stag_size = 0;
  int stag_node = 0;

  rec = SNetHndGetRecord(hnd);

  field_ct = SNetRefTakeData(SNetRecTakeField(rec, F__simpleDes__ct));

  stag_size = SNetRecTakeTag(rec, T__simpleDes__size);

  stag_node = SNetRecTakeTag(rec, T__simpleDes__node);

  return(SNetCall__snet_sink(hnd, field_ct, stag_size, stag_node));
}

static snet_stream_t *SNet__simpleDes___IN___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "snet_source", 
              &SNet__simpleDes__snet_source, 
              &SNetExeRealm_create__snet_source, 
              &SNetExeRealm_update__snet_source, 
              &SNetExeRealm_destroy__snet_source, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__pt, field, F__simpleDes__key, tag, T__simpleDes__size, tag, T__simpleDes__node)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "initP", 
              &SNet__simpleDes__initP, 
              &SNetExeRealm_create__initP, 
              &SNetExeRealm_update__initP, 
              &SNetExeRealm_destroy__initP, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "subRound", 
              &SNet__simpleDes__subRound, 
              &SNetExeRealm_create__subRound, 
              &SNetExeRealm_update__subRound, 
              &SNetExeRealm_destroy__subRound, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(8, field, F__simpleDes__D, field, F__simpleDes__K, tag, T__simpleDes__C, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "finalP", 
              &SNet__simpleDes__finalP, 
              &SNetExeRealm_create__finalP, 
              &SNetExeRealm_update__finalP, 
              &SNetExeRealm_destroy__finalP, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(4, field, F__simpleDes__ct, tag, T__simpleDes__size)));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR___IS(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS___SL, 
              &SNet__simpleDes___IN___SL___SR___IS___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSplitDet(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SR___IS, T__simpleDes__node, T__simpleDes__node);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL___SL, 
              &SNet__simpleDes___IN___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "snet_sink", 
              &SNet__simpleDes__snet_sink, 
              &SNetExeRealm_create__snet_sink, 
              &SNetExeRealm_update__snet_sink, 
              &SNetExeRealm_destroy__snet_sink, 
              SNetIntListListCreate(0));

  return (out_buf);
}

static snet_stream_t *SNet__simpleDes___IN(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__simpleDes___IN___SL, 
              &SNet__simpleDes___IN___SR);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_IN__simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, SNET__simpleDes__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(3, T__simpleDes__mess, T__simpleDes__size, T__simpleDes__num_node), 
                SNetIntListCreate(0)));

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_BODY__simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_IN__simpleDes, 
              &SNet__simpleDes___IN);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_OUT__simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, -SNET__simpleDes__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(0), 
                SNetIntListCreate(0)));

  return (out_buf);
}

snet_stream_t *SNet__simpleDes___simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;
  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_BODY__simpleDes,
              &SNet____SHIELD_OUT__simpleDes);

  return (out_buf);
}

int SNetNetToId(snet_startup_fun_t fun)
{
  if (fun == &SNet__simpleDes___IN___SL___SR___IS) {
    return 1;
  }

  return -1;
}

snet_startup_fun_t SNetIdToNet(int id)
{
  if (id == 1) {
    return &SNet__simpleDes___IN___SL___SR___IS;
  }

  return NULL;
}

int SNetMain__simpleDes(int argc, char* argv[])
{
	FILE *fd;
  char *key = NULL;
  char *value,*hostFL,*masterFL;
  size_t len = 0;
  int numWorkers = 0, numWrappers = 0,dvfs =0, ret = 0;
   
  fd = fopen ("/shared/nil/input.txt","r");

	getline(&key, &len, fd); strtok_r(key, "=", &value); numWorkers=atoi(value);
	getline(&key, &len, fd); strtok_r(key, "=", &value); numWrappers=atoi(value);
	getline(&key, &len, fd); strtok_r(key, "=", &value); dvfs=atoi(value);
  getline(&key, &len, fd); strtok_r(key, "=", &hostFL); hostFL[strcspn ( hostFL, "\n" )] = '\0';
  masterFL = "/shared/nil/Out/master.txt";
  
  printf("work %d wrap %d dvfs %d, host %s, master %s\n\n",numWorkers,numWrappers,dvfs,hostFL,masterFL);
  fflush(stdout);
  SCCInit(numWorkers,numWrappers,dvfs,hostFL,masterFL);

  if(SCCIsMaster()){
		C4SNetInit(I__simpleDes__C4SNet, 0);
  
  	ret = SNetInRun(argc, argv,
              snet_simpleDes_labels,
              SNET__simpleDes__NUMBER_OF_LABELS,
              snet_simpleDes_interfaces,
              SNET__simpleDes__NUMBER_OF_INTERFACES,
              SNet__simpleDes___simpleDes);

  	SNetInterfacesDestroy();
  }else{
    ret = SNetInRunWorker(argc, argv);
  }
  SCCStop();

  return( ret);
}

