/**
 * @file simpleDes.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE simpleDes.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _SIMPLEDES_H_
#define _SIMPLEDES_H_

#include "snetentities.h"
#include "distribution.h"

#define E__simpleDes__NONE 0
#define F__simpleDes__pt 1
#define F__simpleDes__key 2
#define F__simpleDes__D 3
#define F__simpleDes__K 4
#define F__simpleDes__ct 5
#define T__simpleDes__mess 6
#define T__simpleDes__size 7
#define T__simpleDes__num_node 8
#define T__simpleDes__node 9
#define T__simpleDes__C 10

#define SNET__simpleDes__NUMBER_OF_LABELS 11


#define I__simpleDes__C4SNet 0

#define SNET__simpleDes__NUMBER_OF_INTERFACES 1


extern char *snet_simpleDes_labels[];

extern char *snet_simpleDes_interfaces[];


extern snet_stream_t *SNet__simpleDes___simpleDes(snet_stream_t *in_buf, snet_info_t *info, int location);

#endif

