/**
 * @file minic.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE minic.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/
#include <stdlib.h>
#include "minic.h"
#include "type.h"
#include "networkinterface.h"
#include "C4SNet.h"
#include "distribution.h"
#include "list.h"
#include "../scc.h"

char *snet_minic_labels[] = {
	"E__minic__None",
	"A",
	"X"};

char *snet_minic_interfaces[] = {
	"C4SNet"};

extern void *dec(void *hnd, void *arg_0);

static snet_handle_t *SNetExeRealm_create__dec(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__dec(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__dec(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__dec(snet_handle_t *handle, void *arg_0)
{
  return dec(handle, arg_0);
}

static snet_handle_t *SNet__minic__dec(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_A = NULL;

  rec = SNetHndGetRecord(hnd);

  field_A = SNetRefTakeData(SNetRecTakeField(rec, F__minic__A));

  return(SNetCall__dec(hnd, field_A));
}

extern void *init(void *hnd);

static snet_handle_t *SNetExeRealm_create__init(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__init(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__init(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__init(snet_handle_t *handle)
{
  return init(handle);
}

static snet_handle_t *SNet__minic__init(snet_handle_t *hnd)
{
  struct record *rec = NULL;

  rec = SNetHndGetRecord(hnd);

  return(SNetCall__init(hnd));
}

static snet_stream_t *SNet__minic___IN___P1(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "dec", 
              &SNet__minic__dec, 
              &SNetExeRealm_create__dec, 
              &SNetExeRealm_update__dec, 
              &SNetExeRealm_destroy__dec, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(2, field, F__minic__A)));

  return (out_buf);
}

static snet_stream_t *SNet__minic___IN___P2(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "init", 
              &SNet__minic__init, 
              &SNetExeRealm_create__init, 
              &SNetExeRealm_update__init, 
              &SNetExeRealm_destroy__init, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(2, field, F__minic__X)));

  return (out_buf);
}

static snet_stream_t *SNet__minic___IN(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetParallel(in_buf, info, location, 
              SNetVariantListListCreate(2, 
                SNetVariantListCreate(1, 
                  SNetVariantCreate(
                    SNetIntListCreate(1, F__minic__A), 
                    SNetIntListCreate(0), 
                    SNetIntListCreate(0))), 
                SNetVariantListCreate(0)), 
              &SNet__minic___IN___P1, 
              &SNet__minic___IN___P2);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_IN__minic(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, SNET__minic__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(1, F__minic__A), 
                SNetIntListCreate(0), 
                SNetIntListCreate(0)));

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_BODY__minic(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_IN__minic, 
              &SNet__minic___IN);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_OUT__minic(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, -SNET__minic__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(2, F__minic__A, F__minic__X), 
                SNetIntListCreate(0), 
                SNetIntListCreate(0)));

  return (out_buf);
}

snet_stream_t *SNet__minic___minic(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;
  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_BODY__minic,
              &SNet____SHIELD_OUT__minic);

  return (out_buf);
}

int SNetNetToId(snet_startup_fun_t fun)
{
  

  return -1;
}

snet_startup_fun_t SNetIdToNet(int id)
{
  

  return NULL;
}

int SNetMain__minic(int argc, char* argv[])
{
  int i,numWorkers = 0,ret = 0;
  for (i=0; i<argc; i++) {
    if(strcmp(argv[i], "-w") == 0) {
			/* Number of workers */
			i++;
			numWorkers = atoi(argv[i]);
		}
  }
  SCCInit(0,numWorkers,2,"/shared/nil/nk.host");
  
  if(SCCIsMaster()){
    C4SNetInit(I__minic__C4SNet, 0);
    
    ret = SNetInRun(argc, argv,
              snet_minic_labels,
              SNET__minic__NUMBER_OF_LABELS,
              snet_minic_interfaces,
              SNET__minic__NUMBER_OF_INTERFACES,
              SNet__minic___minic);

    SNetInterfacesDestroy();
  }else{
    ret = SNetInRunWorker(argc, argv);
  }
  SCCStop();
  return( ret);
}

